"""
Example: Diplexed TWPA with Peripheral Filters

This example demonstrates how to use the filter_builder module to:
  1. Design LP/HP diplexers (Butterworth, 15th order, 8 GHz crossover)
  2. Generate JC-compatible netlists for the diplexers
  3. Load an existing TWPA netlist (4wm_jtwpa_2002cells_01)
  4. Compose the full topology: diplexer_in -> TWPA -> diplexer_out
  5. Save the composed 4-port netlist for simulation with JosephsonCircuits.jl

The resulting device has 4 external ports:
  Port 1: Input diplexer - LP arm (signal input)
  Port 2: Input diplexer - HP arm (pump + idler input)
  Port 3: Output diplexer - LP arm (signal output)
  Port 4: Output diplexer - HP arm (pump + idler output)

Prerequisites:
  - TWPA netlist: 4wm_jtwpa_2002cells_01.py (in netlists/ folder)
  - Generated by netlist_JC_builder from the 4wm_jtwpa_01 design
"""

import numpy as np
import importlib.util
import os

from twpa_design.filter_builder import (
    FilterSpec,
    design_multiplexer,
    multiplexer_to_netlist,
    compose_chain,
    save_peripheral_netlist,
    plot_peripheral_response,
)
from twpa_design import NETLISTS_DIR

# ============================================================================
# Step 1: Design the diplexers
# ============================================================================
print("=" * 60)
print("Step 1: Designing LP/HP diplexers")
print("=" * 60)

# Both diplexers: Butterworth 25th order, 8.3 GHz crossover, 50 Ohm
fc_Hz = 8.3e9  # 8 GHz crossover frequency

# Each diplexer has 3 ports: common (port 1), and one per arm (ports 2, 3, ...).
# Arm order in arm_specs determines port numbering: first arm -> port 2, second -> port 3.
# After composition, common ports are consumed (they connect to the TWPA),
# and the remaining arm ports are renumbered sequentially across the full device.
# Here LP is first -> gets the lower port numbers, HP second -> higher port numbers.
diplexer_design = design_multiplexer(
    arm_specs=[
        FilterSpec(response='lp', order=25, fc=fc_Hz, approx='butterworth', label='lp'),
        FilterSpec(response='hp', order=25, fc=fc_Hz, approx='butterworth', label='hp'),
    ],
    Z0=50.0,
    label='diplexer_8GHz',
)

print(f"Diplexer designed: {diplexer_design.label}")
print(f"  Arms: {[arm.spec.label for arm in diplexer_design.arms]}")
print(f"  Order: {diplexer_design.arms[0].spec.order}")
print(f"  Crossover: {fc_Hz/1e9:.1f} GHz")

# ============================================================================
# Step 2: Plot standalone diplexer response
# ============================================================================
print("\nStep 2: Plotting standalone diplexer response")
print("=" * 60)

f_plot = np.linspace(0.1, 20, 2001)  # GHz
fig, axes, response = plot_peripheral_response(diplexer_design, f=f_plot, units='GHz')

# ============================================================================
# Step 3: Generate diplexer netlists
# ============================================================================
print("\nStep 3: Generating diplexer netlists")
print("=" * 60)

# Input diplexer (prefix m1) and output diplexer (prefix m2)
diplexer_in = multiplexer_to_netlist(diplexer_design, prefix='m1')
diplexer_out = multiplexer_to_netlist(diplexer_design, prefix='m2')

print(f"Input diplexer:  {diplexer_in.n_ports} ports, {len(diplexer_in.components)} components")
print(f"  Port map: {diplexer_in.port_map}")
print(f"Output diplexer: {diplexer_out.n_ports} ports, {len(diplexer_out.components)} components")
print(f"  Port map: {diplexer_out.port_map}")

# ============================================================================
# Step 4: Load existing TWPA netlist
# ============================================================================
print("\nStep 4: Loading TWPA netlist")
print("=" * 60)

twpa_netlist_name = "4wm_jtwpa_2002cells_01"
twpa_file = os.path.join(str(NETLISTS_DIR), f"{twpa_netlist_name}.py")

# Load the TWPA netlist file as a dict
spec = importlib.util.spec_from_file_location("twpa_netlist", twpa_file)
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)

twpa_netlist = {
    'jc_components': mod.jc_components,
    'circuit_parameters': mod.circuit_parameters,
    'metadata': mod.metadata,
}

print(f"TWPA: {twpa_netlist_name}")
print(f"  Components: {len(twpa_netlist['jc_components'])}")
print(f"  Parameters: {len(twpa_netlist['circuit_parameters'])}")

# ============================================================================
# Step 5: Compose the full topology
# ============================================================================
print("\nStep 5: Composing diplexer -> TWPA -> diplexer")
print("=" * 60)

# Connection map:
#   diplexer_in common port -> TWPA port 1 (all tones enter TWPA)
#   TWPA port 2 -> diplexer_out common port (all tones exit to diplexer)
# The HP and LP arms of each diplexer become the external ports.
jc_components, circuit_parameters, metadata = compose_chain(
    blocks=[diplexer_in, twpa_netlist, diplexer_out],
    connections=[
        ('common', 'input'),   # diplexer_in common -> TWPA input
        ('output', 'common'),  # TWPA output -> diplexer_out common
    ],
)

print(f"Composed circuit:")
print(f"  Total components: {len(jc_components)}")
print(f"  Total parameters: {len(circuit_parameters)}")
print(f"  External ports: {metadata.get('n_ports', '?')}")
print(f"  Port roles: {metadata.get('port_roles', {})}")

# ============================================================================
# Step 6: Save the composed netlist
# ============================================================================
print("\nStep 6: Saving composed netlist")
print("=" * 60)

output_name = "diplexed_4wm_jtwpa_2002cells_01"
output_file = os.path.join(str(NETLISTS_DIR), f"{output_name}.py")

metadata['device_name'] = output_name
metadata['topology'] = 'diplexer_in -> TWPA -> diplexer_out'
metadata['diplexer_order'] = 15
metadata['diplexer_fc_GHz'] = fc_Hz / 1e9
metadata['twpa_netlist'] = twpa_netlist_name

save_peripheral_netlist(jc_components, circuit_parameters, metadata, output_file)

print(f"\nDone! The 4-port diplexed TWPA netlist is saved at:")
print(f"  {output_file}")
print(f"\nPort assignment:")
print(f"  Port 1: LP in  (signal input)")
print(f"  Port 2: HP in  (pump + idler input)")
print(f"  Port 3: LP out (signal output)")
print(f"  Port 4: HP out (pump + idler output)")

# ============================================================================
# Step 7: Simulate with JosephsonCircuits.jl
# ============================================================================
print("\n" + "=" * 60)
print("Step 7: Running Julia simulation")
print("=" * 60)

from twpa_design.julia_wrapper import TWPASimulator, TWPASimulationConfig

simulator = TWPASimulator()

# Simulation config for 4-port diplexed TWPA:
#   Signal enters Port 1 (LP in), exits Port 3 (LP out)
#   Pump enters Port 2 (HP in)
sim_config = TWPASimulationConfig(
    freq_start_GHz=4.0,
    freq_stop_GHz=12.0,
    freq_step_GHz=0.05,
    pump_freq_GHz=8.63,
    pump_current_A=2.7e-6,
    pump_port=2,            # HP in (pump enters through HP arm)
    signal_port=1,          # LP in (signal enters through LP arm)
    output_port=3,          # LP out (signal exits through LP arm)
    Npumpharmonics=20,
    Nmodulationharmonics=10,
)

try:
    results = simulator.run_full_simulation(
        netlist_name=output_name,
        config=sim_config,
        verbose=True,
        save_results=False,
        show_plot=False,    # We'll plot custom figures below
    )

    # ============================================================================
    # Step 8: Plot results
    # ============================================================================
    print("\n" + "=" * 60)
    print("Step 8: Plotting results")
    print("=" * 60)

    # Standard 4-panel plot (uncomment to see built-in S-param/idler/QE panels)
    # results.plot(show_plot=True, max_mode_order_to_plot=4)

    # Custom plots for key diplexer TWPA metrics
    import matplotlib.pyplot as plt
    import matplotlib.ticker as ticker
    import matplotlib.gridspec as gridspec
    from matplotlib.lines import Line2D
    from twpa_design.plots_params import (
        blue, red, green, orange, purple, black,
        linewidth, fontsize, fontsize_title, fontsize_legend
    )

    fig = plt.figure(figsize=(8.6/2.54, 5))
    gs = gridspec.GridSpec(2, 1, figure=fig, height_ratios=[2, 1], hspace=0.5)
    ax1 = fig.add_subplot(gs[0])
    ax2 = fig.add_subplot(gs[1])

    freq = results.frequencies_GHz

    # Panel 1: Key S-parameters for diplexed TWPA
    ax1.plot(freq, 10*np.log10(results.s_param(3, 1)), color=tuple(blue), linewidth=linewidth)
    ax1.plot(freq, 10*np.log10(results.s_param(1, 3)), color=tuple(red), linewidth=linewidth)
    ax1.plot(freq, 10*np.log10(results.s_param(4, 2)), color=tuple(orange), linewidth=linewidth)
    ax1.plot(freq, 10*np.log10(results.s_param(1, 1)), color=tuple(green), linewidth=linewidth, alpha=0.7)
    ax1.plot(freq, 10*np.log10(results.s_param(3, 3)), color=tuple(green), linewidth=linewidth, alpha=0.7, linestyle='--')
    ax1.axvline(sim_config.pump_freq_GHz, color=tuple(purple), linestyle=':', alpha=0.5)

    s31_handle = Line2D([0], [0], color=tuple(blue), linewidth=linewidth, label=r'$|S_{31}|$')
    s13_handle = Line2D([0], [0], color=tuple(red), linewidth=linewidth, label=r'$|S_{13}|$')
    s42_handle = Line2D([0], [0], color=tuple(orange), linewidth=linewidth, label=r'$|S_{42}|$')
    s11_handle = Line2D([0], [0], color=tuple(green), linewidth=linewidth, alpha=0.7, label=r'$|S_{11}|$')
    s33_handle = Line2D([0], [0], color=tuple(green), linewidth=linewidth, alpha=0.7, linestyle='--', label=r'$|S_{33}|$')
    pump_handle = Line2D([0], [0], color=tuple(purple), linestyle=':', alpha=0.5,
                         label=rf'$f_a = {sim_config.pump_freq_GHz}$ GHz')

    ax1.legend(
        handles=[s31_handle, s13_handle, s42_handle, s11_handle, s33_handle, pump_handle],
        loc='lower right',
        fontsize=fontsize_legend,
        frameon=True,
        fancybox=True,
        framealpha=0.7,
        facecolor='white',
        edgecolor='gray',
        borderpad=0.3,
        handlelength=1.5,
        handletextpad=0.5,
        borderaxespad=0.5,
    )
    ax1.set_ylabel(r'$|S|$-parameters [dB]', fontsize=fontsize)
    ax1.set_title('Diplexed TWPA', fontsize=fontsize_title)
    ax1.grid(True, alpha=0.3)
    ax1.set_ylim(-30, 30)
    ax1.set_xlim(sim_config.freq_start_GHz, sim_config.freq_stop_GHz)
    ax1.tick_params(axis='both', labelsize=fontsize)
    ax1.xaxis.set_major_formatter(ticker.FormatStrFormatter('%g'))
    ax1.yaxis.set_major_formatter(ticker.FormatStrFormatter('%g'))

    # Panel 2: Quantum efficiency
    ax2.plot(freq, results.quantum_efficiency, color=tuple(blue), linewidth=linewidth)
    ax2.axhline(1.0, color=tuple(black), linestyle='--', alpha=0.7, label='Ideal')
    ax2.set_xlabel('frequency [GHz]', fontsize=fontsize)
    ax2.set_ylabel(r'$\mathsf{QE}/\mathsf{QE}_\mathsf{ideal}$', fontsize=fontsize)
    ax2.set_title('Quantum Efficiency', fontsize=fontsize_title)
    ax2.grid(True, alpha=0.3)
    ax2.set_ylim(0.7, 1.05)
    ax2.set_yticks([0.7, 0.8, 0.9, 1])
    ax2.set_xlim(sim_config.freq_start_GHz, sim_config.freq_stop_GHz)
    ax2.tick_params(axis='both', labelsize=fontsize)
    ax2.xaxis.set_major_formatter(ticker.FormatStrFormatter('%g'))
    ax2.yaxis.set_major_formatter(ticker.FormatStrFormatter('%g'))

    # Save results and plot
    save_plot = True
    results.save(config=sim_config)
    if save_plot:
        from twpa_design import RESULTS_DIR
        from twpa_design.helper_functions import filecounter
        plot_pattern = f"{RESULTS_DIR}/{output_name}_pump{sim_config.pump_freq_GHz:.2f}GHz_*.svg"
        plot_filename, plot_number = filecounter(plot_pattern)
        fig.savefig(plot_filename, format='svg', bbox_inches='tight')
        print(f"📈 Plot saved to: {plot_filename}")

    plt.show()

    print(f"\n🎯 Diplexed TWPA simulation complete!")

except Exception as e:
    print(f"\n❌ Simulation failed: {e}")
    print("The composed netlist was saved successfully — you can try")
    print("running the simulation manually with different parameters.")
    raise
